server:
  port: 8091

spring:
  datasource:
    name: knowledgebase
    url: jdbc:mysql://127.0.0.1:3306/knowledgebase
    username: root
    password: cong2021
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
  #redis
  redis:
    host: localhost
    port: 6379

mybatis:
  mapper-locations: classpath:mapping/*.xml